name: Test and package Python application


# This makes the script run manually
on:
  workflow_dispatch


jobs:
  run_ls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Check folder
        run: |
          ls -la

  build_executable:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Package Main application as into dist folder with ".exe" file
      run: |
        pyinstaller Main.py

    - name: Commit changes in dist folder with .exe
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Automatic run of tests and creation of executable"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main


  test_calculator:
    runs-on: ubuntu-latest
    steps: 
    - name: Run Calculator tests
      run: |
        python -m unittest Calculator_Test.py
